DATA

In [ ]:
company_detail_list = {
      'Company 1': {
          'name': 'Company 1',
          'domain': 'Retail',
          'clients': [
              {
                  'name': 'acme.inc',
                  'country': 'united states'
              },
              {
                  'name': 'Wayne.co',
                  'country': 'united states'
              }
          ]
      },
      'Company 2': {
          'name': 'Company 2',
          'domain': 'Construction',
          'clients': [
              {
                  'name': 'Tesla',
                  'country': 'united states'
              },
              {
                  'name': 'Japan Airlines',
                  'country': 'japan'
              },
              {
                  'name': 'Indofood',
                  'country': 'indonesia'
              }
          ]
      },
      'Company 3': {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'clients': [
              {
                  'name': 'Petronas',
                  'country': 'malaysia'
              },
              {
                  'name': 'VW Group',
                  'country': 'germany'
              },
              {
                  'name': 'IBM',
                  'country': 'united states'
              },
              {
                  'name': 'Mitsubishi',
                  'country': 'japan'
              }
          ]
      }
  } 
employee_detail_list = {
      'John Doe': {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1'
      },
      'Tom Smith': {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2'
      },
      'Andrew Sebastian': {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 2'
      },
  }


SOAL 1

In [35]:
def sort_company():
    for company_name, company_detail in company_detail_list.items():
        print("Name:", company_detail['name'])
        print("Domain:", company_detail['domain'])
        print()

# Memanggil fungsi untuk mencetak detail perusahaan
sort_company()

Name: Company 1
Domain: Retail

Name: Company 2
Domain: Construction

Name: Company 3
Domain: Healthcare



SOAl 2

In [32]:

def get_company_domain():
    for company_name, company_detail in company_detail_list.items():
        num_clients = len(company_detail['clients'])
        print(f"{company_name}: {company_detail['domain']}, relation: {num_clients} clients")

# Memanggil fungsi untuk mencetak detail perusahaan
get_company_domain()


Company 1: Retail, relation: 2 clients
Company 2: Construction, relation: 3 clients
Company 3: Healthcare, relation: 4 clients


In [ ]:
SOAL 3

In [39]:
def print_employee_company_domain():
    for employee_name, employee_detail in employee_detail_list.items():
        company_name = employee_detail['company']
        company_domain = company_detail_list[company_name]['domain']
        full_name = employee_detail['full_name']
        print(f'"full_name": "{full_name}", "company": "{company_name}", "domain": "{company_domain}"')

# Memanggil fungsi untuk mencetak detail karyawan, perusahaan, dan domain
print_employee_company_domain()

"full_name": "John Doe", "company": "Company 1", "domain": "Retail"
"full_name": "Tom Smith", "company": "Company 2", "domain": "Construction"
"full_name": "Andrew Sebastian", "company": "Company 2", "domain": "Construction"


Soal pre-processing data

In [43]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer 

In [44]:
data = pd.read_csv('50_Startups.csv')

In [45]:
data.head(7)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51

1. Lakukan analisa mengenai field mana saja yang memiliki data kosong(Nan) lalu Isi data yang kosong tersebut menggunakan nilai mean

In [47]:
X = data.head(7).values
X

array([[165349.2, 136897.8, 471784.1, 'New York', 192261.83],
       [162597.7, 151377.59, 443898.53, 'California', 191792.06],
       [153441.51, 101145.55, 407934.54, 'Florida', 191050.39],
       [144372.41, 118671.85, 383199.62, 'New York', 182901.99],
       [142107.34, 91391.77, 366168.42, 'Florida', 166187.94],
       [131876.9, 99814.71, 362861.36, 'New York', 156991.12],
       [134615.46, 147198.87, 127716.82, 'California', 156122.51]],
      dtype=object)

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [56]:
X

array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 136897.8, 471784.1,
        'New York', 192261.83],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 151377.59, 443898.53,
        'California', 191792.06],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 101145.55, 407934.54,
        'Florida', 191050.39],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 118671.85, 383199.62,
        'New York', 182901.99],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 91391.77, 366168.42,
        'Florida', 166187.94],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 99814.71, 362861.36,
        'New York', 156991.12],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 147198.87, 127716.82,
        'California', 156122.51]], dtype=object)

 oneHotEncoder ke field state

OneHOtEncode

In [68]:
label_encoder = LabelEncoder()
X[:, -2] =label_encoder.fit_transform(X[:,-2])
X

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 136897.8, 471784.1, 2,
        192261.83],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 151377.59, 443898.53, 0,
        191792.06],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 101145.55, 407934.54, 1,
        191050.39],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 118671.85, 383199.62, 2,
        182901.99],
       [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 91391.77, 366168.42, 1,
        166187.94],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 99814.71, 362861.36, 2,
        156991.12],
       [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 147198.87, 127716.82, 0,
        156122.51]], dtype=object)

In [69]:
one_hot_encoder = OneHotEncoder(categories=X[0])
ct = ColumnTransformer([("Name_Of_Your_Step", OneHotEncoder(),[0])], remainder="passthrough")
X = ct.fit_transform(X)
# X = one_hot_encoder.fit_transform(X).toarray()
df = pd.DataFrame(X)
df

0    1    2    3    4    5    6    7    8          9          10 11  \
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   136897.8   471784.1  2   
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  151377.59  443898.53  0   
2  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  101145.55  407934.54  1   
3  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  118671.85  383199.62  2   
4  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   91391.77  366168.42  1   
5  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   99814.71  362861.36  2   
6  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  147198.87  127716.82  0   

          12  
0  192261.83  
1  191792.06  
2  191050.39  
3  182901.99  
4  166187.94  
5  156991.12  
6  156122.51

In [70]:
X=X.astype(int)
X

array([[     0,      1,      0,      0,      0,      0,      0,      0,
             1, 136897, 471784,      2, 192261],
       [     0,      1,      0,      0,      0,      0,      0,      1,
             0, 151377, 443898,      0, 191792],
       [     0,      1,      0,      0,      0,      0,      1,      0,
             0, 101145, 407934,      1, 191050],
       [     0,      1,      0,      0,      0,      1,      0,      0,
             0, 118671, 383199,      2, 182901],
       [     0,      1,      0,      0,      1,      0,      0,      0,
             0,  91391, 366168,      1, 166187],
       [     1,      0,      1,      0,      0,      0,      0,      0,
             0,  99814, 362861,      2, 156991],
       [     0,      1,      0,      1,      0,      0,      0,      0,
             0, 147198, 127716,      0, 156122]])

buat field baru yaitu Tax. dimana Tax = (profit + Marketing Spend + administration) * 5%

In [74]:
data = pd.read_csv('50_Startups.csv')
data = (data['Profit'] + data['Marketing Spend'] + data['Administration']) * 0.05

# Output data dengan field "Tax" baru
print(data)

0     40047.1865
1     39353.4090
2     35006.5240
3     34238.6730
4     31187.4065
5     30983.3595
6     21551.9100
7            NaN
8     30627.2005
9     28171.0375
10    24293.8505
11    24289.7280
12    25937.2670
13           NaN
14    27283.1495
15    25715.5055
16    25646.8270
17    27651.1130
18    26668.1130
19           NaN
20    26550.2900
21    28241.1870
22    26822.7130
23           NaN
24           NaN
25    19246.0060
26    19195.9795
27    29302.8335
28    20203.8070
29    18058.7540
30    15335.5055
31           NaN
32    13636.6350
33    20723.5610
34    23260.2195
35    19352.2295
36    20944.5610
37           NaN
38           NaN
39    16949.3575
40    18479.0815
41    16349.0155
42    15784.4615
43    11633.7725
44    12417.0595
45     9549.1525
46    23121.0710
47           NaN
48           NaN
49     8841.9130
dtype: float64


Jalankan standardScaler field-field tersebut


In [71]:
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-4.08248290e-01,  4.08248290e-01, -4.08248290e-01,
        -4.08248290e-01, -4.08248290e-01, -4.08248290e-01,
        -4.08248290e-01, -4.08248290e-01,  2.44948974e+00,
         7.05464447e-01,  1.01241071e+00,  1.02899151e+00,
         1.01388803e+00],
       [-4.08248290e-01,  4.08248290e-01, -4.08248290e-01,
        -4.08248290e-01, -4.08248290e-01, -4.08248290e-01,
        -4.08248290e-01,  2.44948974e+00, -4.08248290e-01,
         1.34513199e+00,  7.44963007e-01, -1.37198868e+00,
         9.83216238e-01],
       [-4.08248290e-01,  4.08248290e-01, -4.08248290e-01,
        -4.08248290e-01, -4.08248290e-01, -4.08248290e-01,
         2.44948974e+00, -4.08248290e-01, -4.08248290e-01,
        -8.73913600e-01,  4.00041214e-01, -1.71498585e-01,
         9.34690723e-01],
       [-4.08248290e-01,  4.08248290e-01, -4.08248290e-01,
        -4.08248290e-01, -4.08248290e-01,  2.44948974e+00,
        -4.08248290e-01, -4.08248290e-01, -4.08248290e-01,
        -9.96861539e-02,  1.62813971e